image: registry.gitlab.com/thegoman/pdf
variables:
  REPO_NAME: gitlab.com/thegoman/pdf

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - format
  - lint
  - test

format:
  stage: format
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

lint:
  stage: lint
  script:
    - golint -set_exit_status $(go list ./... | grep -v /vendor/)

tests:
  stage: test
  script:
    - go test -short $(go list ./... | grep -v /vendor/)

code-coverage:
  stage: test
  script:
    go test -cover -short $(go list ./... | grep -v /vendor/)

race-conditions:
  stage: test
  script:
    - go test -race -short $(go list ./... | grep -v /vendor/)
